CREATE TABLE IF NOT EXISTS pecas (
    id TINYINT PRIMARY KEY,
    value_1 VARCHAR(5) NOT NULL,
    value_2 VARCHAR(5) NOT NULL,
);
INSERT INTO pecas VALUES 
('Base', 'Acido'),
('Base', 'Base'),
('Base', 'Oxido'),
('Base', 'Sal'),
('Base', 'Sal'),
('Base', 'Oxido'),
('Base', 'Base'),
('Base', 'Acido'),
('Acido', 'Acido'),
('Acido', 'Base'),
('Acido', 'Oxido'),
('Acido', 'Sal'),
('Acido', 'Acido'),
('Acido', 'Base'),
('Acido', 'Oxido'),
('Acido', 'Sal'),
('Sal', 'Acido'),
('Sal', 'Base'),
('Sal', 'Sal'),
('Sal', 'Oxido'),
('Sal', 'Acido'),
('Sal', 'Base'),
('Sal', 'Sal'),
('Sal', 'Oxido'),
('Oxido', 'Acido'),
('Oxido', 'Base'),
('Oxido', 'Sal'),
('Oxido', 'Oxido'),
('Oxido', 'Acido'),
('Oxido', 'Base'),
('Oxido', 'Sal'),
('Oxido', 'Oxido');